Update spring to version 3.0.0
This resolve errors like:
/Users/christophernady/.rvm/gems/ruby-3.1.2/gems/spring-2.1.1/lib/spring/application.rb:103:in `block in preload': undefined method `mechanism=' for ActiveSupport::Dependencies:Module

        ActiveSupport::Dependencies.mechanism = :load
                                   ^^^^^^^^^^^^ (NoMethodError)

when running `rake test`.

Also set config.cache_classes to false in config/environments/test.rb
in order to prevent errors like:
/Users/christophernady/.rvm/gems/ruby-3.1.2/gems/spring-3.0.0/lib/spring/application.rb:100:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.
Please, set config.cache_classes to false in config/environments/test.rb.
 (RuntimeError)
	from /Users/christophernady/.rvm/gems/ruby-3.1.2/gems/railties-7.0.5/lib/rails/initializable.rb:32:in `instance_exec'