Fix errors when trying to login
Before, errors like:

```
15:34:01 api.1 | NoMethodError (undefined method `secrets' for #<ReactReduxNbaNewsFeed::Application> 15:34:01 api.1 | 15:34:01 api.1 | config.token_secret_signature_key = -> { Rails.application.secrets.secret_key_base }
```

would occur.

According to Google's AI overview this could occur because of "Rails version compatibility: Rails.application.secrets is deprecated in Rails 7.1 and will be removed in Rails 7.2."