Fix different pronto error
This is an attempt to fix errors like:

```
Run PRONTO_PULL_REQUEST_ID="$(jq --raw-output .number "$GITHUB_EVENT_PATH")" \
  PRONTO_PULL_REQUEST_ID="$(jq --raw-output .number "$GITHUB_EVENT_PATH")" \
  PRONTO_GITHUB_ACCESS_TOKEN="***" \
  pronto run -f github_status github_pr -c origin/master -v
  shell: /usr/bin/bash -e {0}
/opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/cli.rb:65:in `discover': failed to resolve path '/home/runner/work/sports-news-feed/sports-news-feed/-v': No such file or directory (Rugged::OSError)
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/cli.rb:65:in `run'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/bin/pronto:6:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/pronto:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/pronto:25:in `<main>'
Error: Process completed with exit code 1.
```

For example from here: https://github.com/ChristopherJamesN/sports-news-feed/actions/runs/9629218914/job/26558348964?pr=118.