Update rubygems version in `Dockerfile` before installing bunder
This resolves errors like:

```
Step #0 - "build image": nokogiri-1.18.8-x86_64-linux requires rubygems version >= 3.3.22, which is
Step #0 - "build image": incompatible with the current version, 3.3.7
Step #0 - "build image": The command '/bin/sh -c gem install bundler &&   bundle config set --local deployment 'true' &&   bundle config set --local without 'development test' &&   bundle install' returned a non-zero code: 5
Finished Step #0 - "build image"
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 5
Step #0 - "build image":
--------------------------------------------------------------------------------

BUILD FAILURE: Build step failure: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 5
ERROR: (gcloud.builds.submit) build 4f983aa1-d6f7-4db8-9c53-377e8df88e3d completed with status "FAILURE"
```

when running

```
gcloud builds submit --config cloudbuild.yaml \
     --substitutions _SERVICE_NAME=rails-news-feed,_SECRET_NAME=rails-master-key-secret &&
osascript -e 'display notification "Build and push of new sports-news-feed app image has completed."'
```