Remove `node_modules` and `package-lock.json` in client directory
And then re-install dependencies with `npm install`.

I did this after running `arch -x86_64 zsh` and then:

```
nvm uninstall 16.18.0
Uninstalled node v16.18.0
```

and then

```
nvm install 16.18.0
Downloading and installing node v16.18.0...
Downloading https://nodejs.org/dist/v16.18.0/node-v16.18.0-darwin-x64.tar.xz...
######################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v16.18.0 (npm v8.19.2)
```

Since the post-commit build on Github is working, for example here:
https://github.com/ChristopherJamesN/sports-news-feed/actions/runs/5707996673/job/15465227497,
I was hoping that using the same node version used there would work locally
as well. Unfortunately I get the same errors as I did before:

```
 npm start

> client@0.1.0 start
> react-scripts start

/Users/christophernady/Development/code/sports-news-feed/client/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/christophernady/Development/code/sports-news-feed/client/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
```