Delete service worker registration which isnt't working and I'm not sure why it was added in the first place
There is no service-worker.js file in this project, so registerServiceWorker will fail with:

```
registerServiceWorker.js:71 Error during service worker registration:
TypeError: Failed to register a ServiceWorker for scope ('https://rails-news-feed-jt3432sekq-uc.a.run.app/') with script ('https://rails-news-feed-jt3432sekq-uc.a.run.app/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.
(anonymous)	@	registerServiceWorker.js:71
```