(Hopefully) fix github access token
This is an attempt to resolve errors like this:

```
Run pronto run -f github_status github_pr -c origin/master
/opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/octokit-7.2.0/lib/octokit/response/raise_error.rb:14:in `on_complete': POST https://api.github.com/repos/ChristopherJamesN/sports-news-feed/statuses/3975622f822af42f8c5b609545676a22c3621d1d: 403 - Resource not accessible by integration // See: https://docs.github.com/rest/commits/statuses#create-a-commit-status (Octokit::Forbidden)
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/faraday-2.9.2/lib/faraday/middleware.rb:18:in `block in call'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/faraday-2.9.2/lib/faraday/response.rb:42:in `on_complete'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/faraday-2.9.2/lib/faraday/middleware.rb:17:in `call'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/octokit-7.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/octokit-7.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/faraday-retry-2.2.1/lib/faraday/retry/middleware.rb:153:in `call'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/faraday-2.9.2/lib/faraday/rack_builder.rb:152:in `build_response'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/faraday-2.9.2/lib/faraday/connection.rb:444:in `run_request'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/faraday-2.9.2/lib/faraday/connection.rb:280:in `post'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/octokit-7.2.0/lib/octokit/connection.rb:156:in `request'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/octokit-7.2.0/lib/octokit/connection.rb:28:in `post'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/octokit-7.2.0/lib/octokit/client/statuses.rb:43:in `create_status'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/github.rb:59:in `create_commit_status'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/formatter/github_status_formatter.rb:28:in `create_status'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/formatter/github_status_formatter.rb:17:in `block in format'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/formatter/github_status_formatter.rb:16:in `each'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/formatter/github_status_formatter.rb:16:in `format'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto.rb:69:in `block in run'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto.rb:68:in `each'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto.rb:68:in `run'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/cli.rb:70:in `block in run'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `chdir'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `run'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/pronto-0.11.2/bin/pronto:6:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/pronto:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.1.2/x64/bin/pronto:25:in `<main>'
Error: Process completed with exit code 1.
```

An example of this error comes from: https://github.com/ChristopherJamesN/sports-news-feed/actions/runs/9629895294/job/26559854589?pr=118.