Update `Dockerfile` and `Gemfile` to allow deployment to Google Cloud to succeed
Without these changes the deployment via

```
gcloud builds submit --config cloudbuild.yaml \
     --substitutions _SERVICE_NAME=rails-news-feed,_SECRET_NAME=rails-master-key-secret &&
osascript -e 'display notification "Build and push of new sports-news-feed app image has completed."'
```

was failing for various reasons, including

```
Step #0 - "build image": Fetching nokogiri 1.18.8
Step #0 - "build image": Installing nokogiri 1.18.8 with native extensions
Step #0 - "build image": Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
Step #0 - "build image":
Step #0 - "build image": current directory:
Step #0 - "build image": /app/vendor/bundle/ruby/3.1.0/gems/nokogiri-1.18.8/ext/nokogiri
Step #0 - "build image": /usr/local/bin/ruby extconf.rb
Step #0 - "build image": checking for whether -std=c99 is accepted as CFLAGS... yes
Step #0 - "build image": checking for whether -Wno-declaration-after-statement is accepted as CFLAGS...
Step #0 - "build image": yes
Step #0 - "build image": checking for whether -O2 is accepted as CFLAGS... yes
Step #0 - "build image": checking for whether -g is accepted as CFLAGS... yes
Step #0 - "build image": checking for whether -Winline is accepted as CFLAGS... yes
Step #0 - "build image": checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
Step #0 - "build image": checking for whether -Wconversion is accepted as CFLAGS... no
Step #0 - "build image": Building nokogiri using packaged libraries.
Step #0 - "build image": Static linking is enabled.
Step #0 - "build image": Cross build is disabled.
Step #0 - "build image": *** extconf.rb failed ***
Step #0 - "build image": Could not create Makefile due to some reason, probably lack of necessary
Step #0 - "build image": libraries and/or headers.  Check the mkmf.log file for more details.  You may
Step #0 - "build image": need configuration options.
Step #0 - "build image":
Step #0 - "build image": Provided configuration options:
Step #0 - "build image": 	--with-opt-dir
Step #0 - "build image": 	--without-opt-dir
Step #0 - "build image": 	--with-opt-include
Step #0 - "build image": 	--without-opt-include=${opt-dir}/include
Step #0 - "build image": 	--with-opt-lib
Step #0 - "build image": 	--without-opt-lib=${opt-dir}/lib
Step #0 - "build image": 	--with-make-prog
Step #0 - "build image": 	--without-make-prog
Step #0 - "build image": 	--srcdir=.
Step #0 - "build image": 	--curdir
Step #0 - "build image": 	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
Step #0 - "build image": 	--help
Step #0 - "build image": 	--clean
Step #0 - "build image": 	--prevent-strip
Step #0 - "build image": 	--enable-system-libraries
Step #0 - "build image": 	--disable-system-libraries
Step #0 - "build image": 	--use-system-libraries
Step #0 - "build image": 	--enable-system-libraries
Step #0 - "build image": 	--disable-system-libraries
Step #0 - "build image": 	--use-system-libraries
Step #0 - "build image": 	--enable-static
Step #0 - "build image": 	--disable-static
Step #0 - "build image": 	--enable-cross-build
Step #0 - "build image": 	--disable-cross-build
Step #0 - "build image": 	--enable-cross-build
Step #0 - "build image": 	--disable-cross-build
Step #0 - "build image": 	--enable-xml2-legacy
Step #0 - "build image": 	--disable-xml2-legacy
Step #0 - "build image": 	--with-zlib-dir
Step #0 - "build image": 	--without-zlib-dir
Step #0 - "build image": 	--with-zlib-include
Step #0 - "build image": 	--without-zlib-include=${zlib-dir}/include
Step #0 - "build image": 	--with-zlib-lib
Step #0 - "build image": 	--without-zlib-lib=${zlib-dir}/lib
Step #0 - "build image": /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/dependency.rb:301:in `to_specs':
Step #0 - "build image": Could not find 'mini_portile2' (~> 2.8.2) among 86 total gem(s)
Step #0 - "build image": (Gem::MissingSpecError)
Step #0 - "build image": Checked in 'GEM_PATH=/app/vendor/bundle/ruby/3.1.0' , execute `gem env` for more
Step #0 - "build image": information
Step #0 - "build image": from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/dependency.rb:313:in
Step #0 - "build image": `to_spec'
Step #0 - "build image": from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_gem.rb:56:in
Step #0 - "build image": `gem'
Step #0 - "build image": 	from extconf.rb:440:in `process_recipe'
Step #0 - "build image": 	from extconf.rb:892:in `<main>'
Step #0 - "build image":
Step #0 - "build image": To see why this extension failed to compile, please check the mkmf.log which can
Step #0 - "build image": be found here:
Step #0 - "build image":
Step #0 - "build image": /app/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/nokogiri-1.18.8/mkmf.log
Step #0 - "build image":
Step #0 - "build image": extconf failed, exit code 1
Step #0 - "build image":
Step #0 - "build image": Gem files will remain installed in
Step #0 - "build image": /app/vendor/bundle/ruby/3.1.0/gems/nokogiri-1.18.8 for inspection.
Step #0 - "build image": Results logged to
Step #0 - "build image": /app/vendor/bundle/ruby/3.1.0/extensions/x86_64-linux/3.1.0/nokogiri-1.18.8/gem_make.out
Step #0 - "build image":
Step #0 - "build image":   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:125:in `run'
Step #0 - "build image": /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:30:in
Step #0 - "build image": `build'
Step #0 - "build image": /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:206:in
Step #0 - "build image": `build_extension'
Step #0 - "build image": /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:240:in `block in
Step #0 - "build image": build_extensions'
Step #0 - "build image":   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:237:in `each'
Step #0 - "build image": /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:237:in
Step #0 - "build image": `build_extensions'
Step #0 - "build image": /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/installer.rb:844:in
Step #0 - "build image": `build_extensions'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/rubygems_gem_installer.rb:111:in
Step #0 - "build image": `build_extensions'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/rubygems_gem_installer.rb:30:in
Step #0 - "build image": `install'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/source/rubygems.rb:220:in
Step #0 - "build image": `install'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer/gem_installer.rb:55:in
Step #0 - "build image": `install'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer/gem_installer.rb:17:in
Step #0 - "build image": `install_from_spec'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer/parallel_installer.rb:133:in
Step #0 - "build image": `do_install'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer/parallel_installer.rb:118:in
Step #0 - "build image": `install_serially'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer/parallel_installer.rb:94:in
Step #0 - "build image": `call'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer/parallel_installer.rb:66:in
Step #0 - "build image": `call'
Step #0 - "build image":   /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer.rb:198:in `install'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer.rb:84:in `block in
Step #0 - "build image": run'
Step #0 - "build image": /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:835:in `block in
Step #0 - "build image": open_file_with_flock'
Step #0 - "build image":   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:823:in `open'
Step #0 - "build image":   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:823:in `open_file_with_flock'
Step #0 - "build image":   /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:809:in `open_file_with_lock'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/process_lock.rb:13:in `block
Step #0 - "build image": in lock'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/shared_helpers.rb:105:in
Step #0 - "build image": `filesystem_access'
Step #0 - "build image":   /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/process_lock.rb:12:in `lock'
Step #0 - "build image":   /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer.rb:71:in `run'
Step #0 - "build image":   /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/installer.rb:23:in `install'
Step #0 - "build image":   /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli/install.rb:72:in `run'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli.rb:247:in `block in
Step #0 - "build image": install'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/settings.rb:159:in
Step #0 - "build image": `temporary'
Step #0 - "build image":   /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli.rb:246:in `install'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in
Step #0 - "build image": `run'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in
Step #0 - "build image": `invoke_command'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor.rb:538:in
Step #0 - "build image": `dispatch'
Step #0 - "build image":   /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli.rb:35:in `dispatch'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in
Step #0 - "build image": `start'
Step #0 - "build image":   /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli.rb:29:in `start'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/exe/bundle:28:in `block in <top
Step #0 - "build image": (required)>'
Step #0 - "build image": /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/friendly_errors.rb:117:in
Step #0 - "build image": `with_friendly_errors'
Step #0 - "build image":   /usr/local/bundle/gems/bundler-2.6.9/exe/bundle:20:in `<top (required)>'
Step #0 - "build image":   /usr/local/bundle/bin/bundle:25:in `load'
Step #0 - "build image":   /usr/local/bundle/bin/bundle:25:in `<main>'
Step #0 - "build image":
Step #0 - "build image": An error occurred while installing nokogiri (1.18.8), and Bundler cannot
Step #0 - "build image": continue.
Step #0 - "build image":
Step #0 - "build image": In Gemfile:
Step #0 - "build image":   knock was resolved to 2.2.0, which depends on
Step #0 - "build image":     rails was resolved to 7.2.2.1, which depends on
Step #0 - "build image":       actioncable was resolved to 7.2.2.1, which depends on
Step #0 - "build image":         actionpack was resolved to 7.2.2.1, which depends on
Step #0 - "build image":           actionview was resolved to 7.2.2.1, which depends on
Step #0 - "build image":             rails-dom-testing was resolved to 2.3.0, which depends on
Step #0 - "build image":               nokogiri
Step #0 - "build image": The command '/bin/sh -c gem install bundler &&   gem install mini_portile2 --no-document &&   bundle config set --local deployment 'true' &&   bundle config set --local without 'development test' &&   bundle install  --jobs 1' returned a non-zero code: 5
Finished Step #0 - "build image"
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 5
Step #0 - "build image":
--------------------------------------------------------------------------------

BUILD FAILURE: Build step failure: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 5
ERROR: (gcloud.builds.submit) build e2ed7d48-e305-4417-906c-1b2155ee1e9e completed with status "FAILURE"
```