Update to bullseye Debian image and fix nodejs installation in `Dockerfile`
This change fixes errors like:

```
gcloud builds submit --config cloudbuild.yaml \
     --substitutions _SERVICE_NAME=rails-news-feed,_SECRET_NAME=rails-master-key-secret &&
osascript -e 'display notification "Build and push of new sports-news-feed app image has completed."'
Creating temporary archive of 42963 file(s) totalling 462.8 MiB before compression.
Some files were not included in the source upload.

Check the gcloud log [/Users/christophernady/.config/gcloud/logs/2025.08.06/19.07.35.132206.log] to see which files and the contents of the
default gcloudignore file used (see `$ gcloud topic gcloudignore` to learn
more).

Uploading tarball of [.] to [gs://news-feed-368501_cloudbuild/source/1754525255.490968-2083d02701984c58a1275989b0c2d610.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/news-feed-368501/locations/global/builds/10e16dad-9c91-4619-9139-abcfe873b3f1].
Logs are available at [ https://console.cloud.google.com/cloud-build/builds/10e16dad-9c91-4619-9139-abcfe873b3f1?project=65433380411 ].
Waiting for build to complete. Polling interval: 1 second(s).
----------------------------- REMOTE BUILD OUTPUT ------------------------------
starting build "10e16dad-9c91-4619-9139-abcfe873b3f1"

FETCHSOURCE
Fetching storage object: gs://news-feed-368501_cloudbuild/source/1754525255.490968-2083d02701984c58a1275989b0c2d610.tgz#1754525302318716
Copying gs://news-feed-368501_cloudbuild/source/1754525255.490968-2083d02701984c58a1275989b0c2d610.tgz#1754525302318716...
\ [1 files][ 86.1 MiB/ 86.1 MiB]
Operation completed over 1 objects/86.1 MiB.
BUILD
Starting Step #0 - "build image"
Step #0 - "build image": Already have image (with digest): gcr.io/cloud-builders/docker
Step #0 - "build image": Sending build context to Docker daemon    522MB
Step #0 - "build image": Step 1/15 : FROM ruby:3.1.2-buster
Step #0 - "build image": 3.1.2-buster: Pulling from library/ruby
Step #0 - "build image": 2730d739afad: Pulling fs layer
Step #0 - "build image": a122751b3533: Pulling fs layer
Step #0 - "build image": 0a277c3efe7c: Pulling fs layer
Step #0 - "build image": 25c35b81c503: Pulling fs layer
Step #0 - "build image": cb8cde86ddb2: Pulling fs layer
Step #0 - "build image": 1b4693b2324f: Pulling fs layer
Step #0 - "build image": fad81cb7cfcf: Pulling fs layer
Step #0 - "build image": 2a29ccfe3bcb: Pulling fs layer
Step #0 - "build image": 25c35b81c503: Waiting
Step #0 - "build image": cb8cde86ddb2: Waiting
Step #0 - "build image": 1b4693b2324f: Waiting
Step #0 - "build image": fad81cb7cfcf: Waiting
Step #0 - "build image": 2a29ccfe3bcb: Waiting
Step #0 - "build image": a122751b3533: Download complete
Step #0 - "build image": 0a277c3efe7c: Verifying Checksum
Step #0 - "build image": 0a277c3efe7c: Download complete
Step #0 - "build image": 2730d739afad: Download complete
Step #0 - "build image": 1b4693b2324f: Verifying Checksum
Step #0 - "build image": 1b4693b2324f: Download complete
Step #0 - "build image": 25c35b81c503: Verifying Checksum
Step #0 - "build image": 25c35b81c503: Download complete
Step #0 - "build image": 2a29ccfe3bcb: Verifying Checksum
Step #0 - "build image": 2a29ccfe3bcb: Download complete
Step #0 - "build image": fad81cb7cfcf: Verifying Checksum
Step #0 - "build image": fad81cb7cfcf: Download complete
Step #0 - "build image": 2730d739afad: Pull complete
Step #0 - "build image": a122751b3533: Pull complete
Step #0 - "build image": cb8cde86ddb2: Verifying Checksum
Step #0 - "build image": cb8cde86ddb2: Download complete
Step #0 - "build image": 0a277c3efe7c: Pull complete
Step #0 - "build image": 25c35b81c503: Pull complete
Step #0 - "build image": cb8cde86ddb2: Pull complete
Step #0 - "build image": 1b4693b2324f: Pull complete
Step #0 - "build image": fad81cb7cfcf: Pull complete
Step #0 - "build image": 2a29ccfe3bcb: Pull complete
Step #0 - "build image": Digest: sha256:1c24e30299029b6b8f3662eaa77c8a1ce7f414710dfd70be4d4f2033783278db
Step #0 - "build image": Status: Downloaded newer image for ruby:3.1.2-buster
Step #0 - "build image":  ---> 474fdda17151
Step #0 - "build image": Step 2/15 : RUN (curl -sS https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | apt-key add -) &&   echo "deb https://deb.nodesource.com/node_14.x buster main"      > /etc/apt/sources.list.d/nodesource.list &&   apt-get update && apt-get install -y nodejs lsb-release
Step #0 - "build image":  ---> Running in 69d86d28a1f2
Step #0 - "build image": Warning: apt-key output should not be parsed (stdout is not a terminal)
Step #0 - "build image": OK
Step #0 - "build image": Ign:1 http://deb.debian.org/debian buster InRelease
Step #0 - "build image": Ign:2 http://deb.debian.org/debian-security buster/updates InRelease
Step #0 - "build image": Ign:3 http://deb.debian.org/debian buster-updates InRelease
Step #0 - "build image": Err:4 http://deb.debian.org/debian buster Release
Step #0 - "build image":   404  Not Found [IP: 151.101.2.132 80]
Step #0 - "build image": Err:5 http://deb.debian.org/debian-security buster/updates Release
Step #0 - "build image":   404  Not Found [IP: 151.101.2.132 80]
Step #0 - "build image": Err:6 http://deb.debian.org/debian buster-updates Release
Step #0 - "build image":   404  Not Found [IP: 151.101.2.132 80]
Step #0 - "build image": Get:7 https://deb.nodesource.com/node_14.x buster InRelease [4584 B]
Step #0 - "build image": Get:8 https://deb.nodesource.com/node_14.x buster/main amd64 Packages [776 B]
Step #0 - "build image": Reading package lists...
Step #0 - "build image": E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
Step #0 - "build image": E: The repository 'http://deb.debian.org/debian-security buster/updates Release' does not have a Release file.
Step #0 - "build image": E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
Step #0 - "build image": The command '/bin/sh -c (curl -sS https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | apt-key add -) &&   echo "deb https://deb.nodesource.com/node_14.x buster main"      > /etc/apt/sources.list.d/nodesource.list &&   apt-get update && apt-get install -y nodejs lsb-release' returned a non-zero code: 100
Finished Step #0 - "build image"
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 100
Step #0 - "build image":
--------------------------------------------------------------------------------

BUILD FAILURE: Build step failure: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 100
ERROR: (gcloud.builds.submit) build 10e16dad-9c91-4619-9139-abcfe873b3f1 completed with status "FAILURE"
```

when running

```
gcloud builds submit --config cloudbuild.yaml \
     --substitutions _SERVICE_NAME=rails-news-feed,_SECRET_NAME=rails-master-key-secret &&
osascript -e 'display notification "Build and push of new sports-news-feed app image has completed."'
```