Update `rubygems` in `Dockerfile` before running `bundle install`
This attempts to resolve errors like:

```
Step #0 - "build image": Fetching https://github.com/nsarno/knock
Step #0 - "build image": nokogiri-1.18.9-x86_64-linux requires rubygems version >= 3.3.22, which is
Step #0 - "build image": incompatible with the current version, 3.3.7
Step #0 - "build image": The command '/bin/sh -c gem update --system &&   gem install bundler &&   bundle config set --local deployment 'true' &&   bundle config set --local without 'development test' &&   bundle install' returned a non-zero code: 5
Finished Step #0 - "build image"
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 5
Step #0 - "build image":
```

but it still fails due to

```
Step #0 - "build image":  ---> Running in cbc90b634fcc
Step #0 - "build image": ERROR:  Error installing rubygems-update:
Step #0 - "build image": 	rubygems-update-3.7.1 requires Ruby version >= 3.2.0. The current ruby version is 3.1.2.20.
Step #0 - "build image": Updating rubygems-update
```